### ISSUE TITLE
Usage based unlock

### ISSUE THREAD

**Issue by jonathanKingston** [projectsbyif/data-permissions-catalogue#16]
Often it doesn't make sense to bombard users with permission requests so devices are now taking metrics into account before even permitting the user access to the feature.

An example of this is progressive web app install prompt experiment by Chrome:
https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android?hl=en
Amongst the other restrictions there is: "The user has visited your site twice over two separate days during the course of two weeks."

**Comment by ihutc** [comment]
Added in our big update
