### ISSUE TITLE
Rename "Fact Threshold / smart contracts + data"

### ISSUE THREAD

**Issue by bnvk** [projectsbyif/data-permissions-catalogue#3]
I find this title to be a bit confusing / unclear when what it's talking about is really interesting future stuff... These suggestions are based on the concept of **access** and **smart** as those seem the core of the concept!
- Automated Access Control
- Access Control Threshold
- Threshold Permissions
- Threshold Based Data Access
- Smart Access
- Smart Contract Access
- Autonomous Data Access

**Comment by richardjpope** [comment]
changed
