### ISSUE TITLE
Add 2fa

### ISSUE THREAD

**Issue by richardjpope** [projectsbyif/data-permissions-catalogue#7]
"Two-Factor Authentication
A person provides authentication based on two touchpoints, usually a username & password generating a unique code sent by SMS to be input?
https://en.wikipedia.org/wiki/Two-factor_authentication

Example
Coinbase Login / Transactions

(Again this is more of an identify verification thing but perhaps could also be used to describe for example ‘What’s your postcode?’ and ‘What’s your secret word?’ for an operator to access someone’s account)"

**Comment by ihutc** [comment]
Added in the big update
